const styles = {
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
    paddingTop: 10,
  },
  screenText: {
    color: '#353535',
    fontSize: 18,
  },
  profileScreen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    backgroundColor: '#D9D9D9',
  },
  header: {
    paddingTop: 40,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderBottomColor: '#3C6E71',
    backgroundColor: '#284B63',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '300',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  tabBar: {
    backgroundColor: '#284B63',
    borderTopColor: '#3C6E71',
    borderTopWidth: 1,
    paddingBottom: 5,
    paddingTop: 5,
  },
  registerButton: {
    width: '50',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3C6E71',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    minWidth: 200,
  },
  loginButton: {
    width: 'auto',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#284B63',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    minWidth: 200,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '300',
  },
  buttonPressed: {
    opacity: 0.7,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '90%',
    height: 'auto',
    textAlign: 'center'
  },
  modalText: {
    color: '#353535',
    textAlign: 'center',
    fontSize: 20,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    width: '95%',
  },
  searchInput: {
    flex: 1,
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: '#353535',
    borderWidth: 1,
    borderColor: '#284B63',
    marginRight: 10,
    height: 40,
  },
  searchButton: {
    backgroundColor: '#284B63',
    borderRadius: 10,
    padding: 13,
    alignItems: 'center',
    justifyContent: 'center',
    height: 45,
    width: 50,
  },
  searchButtonPressed: {
    opacity: 0.8,
  },
  categoryItem: {
    width: '90%',
    height: '20%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  categoryName: {
    fontSize: 22,
    fontWeight: '300',
    color: '#353535',
  },
  categoriesContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryPressed: {
    opacity: 0.8,
  },
  topBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: '2%',
    paddingBottom: '2%',
    backgroundColor: '#FFFFFF',
  },
  topBarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingVertical: 8,
    borderColor: '#284B63',
    borderWidth: 1,
    justifyContent: 'center',
  },
  topBarButtonText: {
    color: '#284B63',
    fontSize: 16,
    fontWeight: '300',
  },
  backButton: {
    minWidth: 90,
  },
  cartButton: {
    minWidth: 90,
  },
  categoryTitle: {
    fontSize: 20,
    fontWeight: '300',
    color: '#284B63',
    textAlign: 'center',
  },
  categoryScreen: {
    flex: 1,
    backgroundColor: '#D9D9D9',
  },
  productsList: {
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  productsRow: {
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    width: '48%',
    minHeight: 180,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    marginTop: '4%',
  },
  productCardPressed: {
    opacity: 0.8,
  },
  productImageContainer: {
    width: '100%',
    height: 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  productInfo: {
    flex: 1,
  },
  productName: {
    fontSize: 16,
    fontWeight: '400',
    color: '#353535',
    marginBottom: 5,
    height: 40,
  },
  productDetails: {
    fontSize: 12,
    color: '#666',
    marginBottom: 8,
  },
  productPrice: {
    fontSize: 18,
    fontWeight: '500',
    color: '#284B63',
    marginTop: 'auto',
  },
  noProductsText: {
    fontSize: 18,
    color: '#666',
    textAlign: 'center',
    marginTop: 50,
  },
  productModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  productModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  productModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  productModalTitle: {
    fontSize: 20,
    fontWeight: '500',
    color: '#353535',
  },
  modalProductImageContainer: {
    width: '100%',
    height: 150,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    alignSelf: 'center',
  },
  modalProductName: {
    fontSize: 22,
    fontWeight: '400',
    color: '#353535',
    textAlign: 'center',
    marginBottom: 5,
  },
  modalProductId: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalProductPrice: {
    fontSize: 26,
    fontWeight: '600',
    color: '#284B63',
    textAlign: 'center',
    marginBottom: 20,
  },
  productParamsContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
  },
  productParam: {
    fontSize: 16,
    color: '#353535',
    marginBottom: 8,
  },
  addToCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3C6E71',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  addToCartButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '400',
    marginLeft: 10,
  },
  cartModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  cartModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  cartModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  cartModalTitle: {
    fontSize: 20,
    fontWeight: '500',
    color: '#353535',
  },
  cartItemsList: {
    maxHeight: 300,
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  cartItemImage: {
    width: 50,
    height: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontSize: 16,
    fontWeight: '400',
    color: '#353535',
    marginBottom: 4,
  },
  cartItemPrice: {
    fontSize: 14,
    fontWeight: '500',
    color: '#284B63',
    marginBottom: 4,
  },
  cartItemDetail: {
    fontSize: 12,
    color: '#666',
  },
  cartItemControls: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  cartItemButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  deleteButton: {
    backgroundColor: '#FFF5F5',
    marginLeft: 10,
  },
  cartItemQuantity: {
    fontSize: 16,
    fontWeight: '500',
    color: '#353535',
    marginHorizontal: 10,
    minWidth: 20,
    textAlign: 'center',
  },
  cartTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    marginTop: 10,
  },
  cartTotalText: {
    fontSize: 18,
    fontWeight: '500',
    color: '#353535',
  },
  cartTotalPrice: {
    fontSize: 22,
    fontWeight: '600',
    color: '#284B63',
  },
  cartButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  cartActionButton: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearCartButton: {
    backgroundColor: '#F5F5F5',
    marginRight: 10,
  },
  orderButton: {
    backgroundColor: '#3C6E71',
    marginLeft: 10,
  },
  clearCartButtonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '400',
  },
  orderButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
  },
  emptyCart: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
  },
  emptyCartText: {
    fontSize: 18,
    color: '#666',
    marginTop: 20,
  },
  screenTitle: {
  fontSize: 28,
  fontWeight: 'bold',
  color: '#284B63',
  textAlign: 'center',
  marginBottom: 25,
  marginTop: 10,
  },
  promoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  promoCardPressed: {
    opacity: 0.9,
  },
  promoContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  promoTextContainer: {
    flex: 1,
    marginLeft: 15,
    marginRight: 10,
  },
  promoTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#284B63',
    marginBottom: 5,
  },
  promoSubtitle: {
    fontSize: 16,
    color: '#FF6B6B',
    fontWeight: '600',
    marginBottom: 3,
  },
  promoPeriod: {
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#353535',
    marginBottom: 10,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 15,
    color: '#666',
    lineHeight: 22,
    textAlign: 'center',
  },
  quickLinks: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quickLinksTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#353535',
    marginBottom: 15,
    textAlign: 'center',
  },
  quickLinksContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  quickLinkItem: {
    alignItems: 'center',
    padding: 10,
  },
  quickLinkText: {
    fontSize: 14,
    color: '#284B63',
    marginTop: 8,
    fontWeight: '500',
  },
  promoModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  promoModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxHeight: '80%',
  },
  promoModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  promoModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#284B63',
  },
  promoModalIcon: {
    alignItems: 'center',
    marginBottom: 15,
  },
  promoModalPeriod: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FF6B6B',
    textAlign: 'center',
    marginBottom: 20,
    backgroundColor: '#FFF5F5',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    alignSelf: 'center',
  },
  promoDetails: {
    marginBottom: 20,
  },
  promoDetailItem: {
    fontSize: 16,
    color: '#353535',
    marginBottom: 12,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#FFD700',
  },
  promoModalNote: {
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 25,
    padding: 12,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
  },
  promoModalButton: {
    backgroundColor: '#3C6E71',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  promoModalButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '500',
  },
}

export {styles};